// Generates src/route-manifest.generated.ts — a build artifact, not checked
// into git (see .gitignore), regenerated fresh before every bundled build.
//
// Why this exists at all: mount.ts's normal (unbundled, dev/Docker) path
// mounts routes via `import(filePath)` where filePath is a string computed
// at *runtime* from a Bun.Glob scan of vendor/umami/src/app/api. That's
// deliberately lazy (see mount.ts's own comment on mountUmamiRoutes), but a
// runtime-computed import specifier is invisible to any bundler's static
// analysis — esbuild/rolldown/bun build can't trace it, so none of what a
// route.ts transitively imports (Prisma, bcryptjs, jsonwebtoken, ...) ever
// enters the bundle graph. A bundled build of src/index.ts therefore doesn't
// actually contain the vendored code at all, defeating the point of
// bundling: everything Prisma-backed still needs node_modules on disk at
// runtime, no smaller than an unbundled deploy.
//
// The fix (same pattern Nuxt uses for its file-based routing under the
// hood): emit one `import("literal/relative/path.ts")` per route — a
// *string literal*, not a variable — so the bundler's static analysis can
// see it, follow it, and inline everything it needs. Each loader stays a
// separate `import()` (not a top-level static import), so bundlers that
// support code-splitting still defer evaluating a route's module until its
// first real request — same lazy semantics as the unbundled path, just
// discoverable at bundle time instead of invisible to it. Verified this
// holds (not just assumed) for a single-file esbuild/tsdown output too: see
// the "bundled cold RSS" check in the project's own investigation notes —
// dynamically-imported modules inlined into one file are still wrapped in a
// lazily-invoked init function, not eagerly evaluated at top level.
import { COLLECT_ROOT, COLLECT_ROUTES, API_ROOT, scanApiRoutes, type ApiRouteInfo } from "../src/mount";

const OUT_PATH = `${import.meta.dir}/../src/route-manifest.generated.ts`;

function emitEntries(infos: ApiRouteInfo[], root: string, rootLiteral: string): string {
  return infos
    .map((info) => {
      const importSpecifier = `${rootLiteral}/${info.file}`;
      return `  entry(${JSON.stringify(info.path)}, ${JSON.stringify(info.methods)}, () => import(${JSON.stringify(importSpecifier)})),`;
    })
    .join("\n");
}

const apiInfos = await scanApiRoutes();

let out = `// AUTO-GENERATED by scripts/generate-route-manifest.ts — do not edit, do not commit.\n`;
out += `// Regenerate with: bun scripts/generate-route-manifest.ts\n`;
out += `import type { RouteEntry } from "./mount";\n\n`;
out += `function entry(path: string, methods: readonly string[], load: () => Promise<any>): RouteEntry {\n`;
out += `  let modPromise: Promise<any> | undefined;\n`;
out += `  return { path, methods, load: () => (modPromise ??= load()) };\n`;
out += `}\n\n`;
out += `export const apiRouteManifest: RouteEntry[] = [\n`;
out += emitEntries(apiInfos, API_ROOT, "../vendor/umami/src/app/api");
out += `\n];\n\n`;
out += `export const collectRouteManifest: RouteEntry[] = [\n`;
out += emitEntries(COLLECT_ROUTES, COLLECT_ROOT, "../vendor/umami/src/app/(collect)");
out += `\n];\n`;

await Bun.write(OUT_PATH, out);
console.log(`Generated route-manifest.generated.ts — ${apiInfos.length} api routes + ${COLLECT_ROUTES.length} collect routes`);
